### ISSUE TITLE
Add swagger documentation for API

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/fetch#13]
**Is your feature request related to a problem? Please describe.**
To improve the usability of fetch, swagger documentation would be helpful to list and keep updated all the documentation regarding the endpoints and data schemas that are expected and returned.

**Additional context**
The original inspiration for Fetch comes from the swagger file: https://github.com/Kaleido-Biosciences/Atlas/blob/develop/api/fetch_api.yaml

**Comment by wfowlks** [comment]
This was partially implemented by #18 however better documentation could be had, so leaving this open

**Comment by Caps-Looking** [comment]
Can I take this one?

**Comment by wfowlks** [comment]
> Can I take this one?

Sure!

**Comment by Caps-Looking** [comment]
I'm facing problems to do the project setup, specifically with the Kapture Client.
Can you please help me explaining how to set this guy up?

**Comment by wfowlks** [comment]
Sorry for the delay, Thanks for bringing this to our attention. We have been using an internal repository, however give me a second and I'll set up `kapture-client` to pull from the new GitHub maven repositories. I'll update you when complete, it shouldn't take me to long to set that up.

**Comment by wfowlks** [comment]
I have setup the `kapture-client` to deploy to the new GitHub Package Repository, so now if you pull the newest version of develop or master this project should compile with `mvn clean verify`

**Comment by Caps-Looking** [comment]
Well, I'm facing this problem:
`Could not transfer artifact com.kaleido:kapture-client:pom:3.2.18 from/to github (https://maven.pkg.github.com/Kaleido-Biosciences/kapture-client): Not authorized`

**Comment by wfowlks** [comment]
So I looked into this. It appears that to install from the GitHub Package Repository that you need to authenticate with GitHub per [this ticket](https://github.community/t5/GitHub-API-Development-and/Download-from-Github-Package-Registry-without-authentication/m-p/35501#M3312).

This is not optimal, and so we are looking to deploy the `kapture-client` to maven central so that its a public repository and will not require authentication. I will be working on this and should have it done shortly. 

Thanks for helping us find these issues, and sorry for the inconvenience

**Comment by wfowlks** [comment]
I have made `kapture-client` available on Maven Central. I have removed the repository from the pom.xml file so it will no longer try to get that one, and I just tested downloading from maven central and was able to pull in the `kapture-client` dependency. Please let me know if you have any other issues.

And thanks for your help :)
