### ISSUE TITLE
Refactor controller logic into service classes

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/fetch#25]
**Is your feature request related to a problem? Please describe.**
There is a lot of business logic inside the controller classes, and initially it was fine. However as we start to expand the endpoints, it will make the controllers a bit more readable to move the business logic to service classes

**Describe the solution you'd like**
Refactor the business logic out of the controller classes into service classes

**Additional context**
There are a few other tickets that will be adding endpoints so having modular services will be extremely helpful.

**Comment by wfowlks** [comment]
@Caps-Looking does this look good?

**Comment by Caps-Looking** [comment]
Yeah! That looks great!
