### ISSUE TITLE
Refactor and create client for Cabinet

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/fetch#32]
We should refactor this and create a rest client for Cabinet. Initially we can just have it within the fetch project but further refactoring may be needed to create it in it's own project so that it can be used by other projects and applications. 

Since it seems like we have a bunch of code copy/paste, should we abstract this out to a cabinet client? For the first iteration, I don't think we need a separate project/dependency, however we should probably make it it's own class.

_Originally posted by @wfowlks in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjM2MDU5MjQ1OnYy/pull_request_review_threads/discussion_

**Comment by QpYujin** [comment]
Almost done with the first iteration for the client, then will test it before pushing by end of day

**Comment by QpYujin** [comment]
First iteration of cabinet client is pushed to feature/cabinetClient, it also includes kapture-client code appropriated for cabinet to be used for next stage of cabinetClient
