### ISSUE TITLE
Add barcodes to activity domain object

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/fetch#34]
**Is your feature request related to a problem? Please describe.**
We now have barcodes that are associated with an activity. We would like to add these barcodes to the data structure of the activity when they are retrieved/returned to the caller. 

**Describe the solution you'd like**
Barcodes are apart of the [Platemap](https://github.com/Kaleido-Biosciences/kapture-client/blob/develop/src/main/java/com/kaleido/kaptureclient/domain/Platemap.java#L33) data model in the Kapture-Client. We want to add the List of associated barcodes to the [Activity Domain object](https://github.com/Kaleido-Biosciences/fetch/blob/develop/src/main/java/com/kaleido/fetch/domain/Activity.java). 

You will need to add these barcodes when the activity is requested

**Comment by QParavin** [comment]
updated ticket 39 will work on this next
