### ISSUE TITLE
Add Status to ActivitySummary

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/fetch#36]
**Is your feature request related to a problem? Please describe.**
The ActivitySummary class needs to refer to draft and completed versions in one list

**Describe the solution you'd like**
[ActivitySummary](https://github.com/Kaleido-Biosciences/fetch/blob/develop/src/main/java/com/kaleido/fetch/domain/ActivitySummary.java) should change the attribute **completedVersions** to **versions** and update any references.

**Additional context**
We'll also need an Endpoint to retrieve the activity summaries from Cabinet.  It needs to combine information from the kapture client experiment as well as the information from the endpoint this ticket will create.
https://github.com/Kaleido-Biosciences/cabinet/issues/10

**Comment by QParavin** [comment]
Added the endpoint ("/activitySummary/{activityName}") in feature/ActivitySummary
and get  methods in Activity Service.
