### ISSUE TITLE
Update ActivityVersions

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/fetch#37]
ActivityVersions will now be encompassing the status which entails it DRAFT or COMPLETED, and is going to be implemented in #36. 

Since it is more generic, we should update references in comments and variables: 

- [ ] [ActivitySummary](https://github.com/Kaleido-Biosciences/fetch/blob/develop/src/main/java/com/kaleido/fetch/domain/ActivitySummary.java) refactor completedVersions -> versions

- [ ] [Activity](https://github.com/Kaleido-Biosciences/fetch/blob/develop/src/main/java/com/kaleido/fetch/domain/Activity.java) refactor completedVersions -> versions

Additionally the comments should be updated as well

**Comment by QParavin** [comment]
checked the updated Activity Summary Object in  feature/activitySummary
