### ISSUE TITLE
Add Barcode resource/endpoint

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/fetch#39]
Since we are now getting barcodes from Kapture by the activity. It would be helpful to create an additional endpoint to retrieve just the barcodes associated with an activity. The reason for this is that the user may need to refresh the barcodes without wanting to reload the whole activity. 

We should add an endpoint something like `/activity/barcodes/{activityName}`

Which will return a list of barcodes associated with the activity

**Comment by QParavin** [comment]
Added barcodes to Fetch Service

Added endpoint "/activity/barcodes/{activityName}" in FetchResource
Added getAllbarcodesForActivity method in Fetch to retrieve barcodes from Kapture
