### ISSUE TITLE
Add endpoint for retrieving information by id and classification

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/fetch#4]
**Describe the solution you'd like**
From [Atlas](https://github.com/Kaleido-Biosciences/Atlas), when loading an experiment, we need an endpoint to be able to fetch the information surrounding an `id` and `classification`. 

The endpoint should take an array of tuples/JSON objects that contain the fields: 

- **id** - Some identification number for fetch to retrieve

- **classification** - Some way for Fetch to know where to find the given id

It should return an array of the full objects similar to the query endpoint

**Comment by psk788** [comment]
Closed in Version 0.0.2
