### ISSUE TITLE
Endpoint for saving platemap

### ISSUE THREAD

**Issue by wfowlks** [Kaleido-Biosciences/fetch#6]
**Is your feature request related to a problem? Please describe.**
Currently we are writing directly to DynamoDB from [Atlas](https://github.com/Kaleido-Biosciences/Atlas), which is not optimal if we are trying to modularize it, as it puts a direct dependency on DynamoDB

**Describe the solution you'd like**
Add an endpoint for saving the plate map whenever an action is taken, and also an endpoint for when the plate is marked as completed

POST `/save/draft` - should take a platemap and write it out, and return a timestamp of the save time
POST `/save/complete` - should save the platemap as completed (I.E. Keep a version of it)
GET `/save/{id}` - returns all save timestamps for the given activity id

**Comment by QpYujin** [comment]
Hey Wes, would you consider using a pub/sub like rabbitmq for fetch?

**Comment by QpYujin** [comment]
Pushed new code to the branch, still on current branch as I created the apis, have 3 apis that adds/updates platemaps, and 1 stub api for getting platemap based on activity name, but currently it retrieves all platemaps as I don't have the api to call for retrieving in cabinet

**Comment by QpYujin** [comment]
Latest code integrated with cabinet api to retrieve platemap data based on activity name, this is a POST call
`API Request Body { "id": , "status": , "lastModified": , "checksum": , "activityName": , "data": }`, omit the non-required key/value pair (don't leave empty value), depending on search requirements, the provided body are just all the possible search combination
